# Конфигурация golangci-lint для проекта PR Reviewer Service
# golangci-lint - это агрегатор множества линтеров для Go

# Версия конфигурации (для golangci-lint v2.x)
version: "2"

run:
  # Максимальное время выполнения линтеров (предотвращает зависание в CI/CD)
  timeout: 5m
  
  # Проверять тестовые файлы (*_test.go)
  tests: true
  
  # Режим загрузки модулей: readonly не изменяет go.mod/go.sum при запуске линтера
  modules-download-mode: readonly

linters-settings:
  # errcheck - проверяет, что все ошибки обрабатываются
  errcheck:
    # Проверять type assertions (v, ok := x.(Type))
    # Пример ошибки: v := x.(string) без проверки ok
    check-type-assertions: true
    
    # Проверять присваивания в blank identifier (_)
    # Пример ошибки: _ = someFunc() где someFunc возвращает error
    check-blank: true
  
  # govet - официальный инструмент Go для поиска подозрительных конструкций
  govet:
    # Включить все проверки govet
    enable-all: true
    
    # Отключить fieldalignment (проверка оптимального выравнивания полей структур)
    # Причина: часто ложные срабатывания, читаемость важнее оптимизации памяти
    disable:
      - fieldalignment
  
  # gocyclo - измеряет цикломатическую сложность функций
  gocyclo:
    # Минимальная сложность для предупреждения
    # 15+ означает функция слишком сложная и требует рефакторинга
    # Рекомендуется: < 10 простая, 10-15 нормальная, >15 сложная
    min-complexity: 15
  
  # goconst - находит повторяющиеся строковые константы, которые следует вынести
  goconst:
    # Минимальная длина строки для проверки (игнорирует короткие строки типа "id")
    min-len: 3
    
    # Минимальное число повторений для срабатывания
    # Если строка встречается 3+ раза, предлагается вынести в константу
    min-occurrences: 3
  
  # misspell - проверяет орфографию в комментариях и строках
  misspell:
    # Локаль для проверки (US = американский английский)
    # Пример: найдёт "colour" и предложит "color"
    locale: US
  
  # lll - проверяет длину строк кода
  lll:
    # Максимальная длина строки в символах
    # 120 символов - компромисс между читаемостью и современными мониторами
    # Стандарт Go: 80-120, мы используем 120 для удобства
    line-length: 120
  
  # goimports - автоматически форматирует импорты и группирует их
  goimports:
    # Локальные префиксы для группировки импортов
    # Импорты с этим префиксом будут в отдельной группе после stdlib и внешних пакетов
    # Порядок: stdlib -> внешние -> test_avito
    local-prefixes: test_avito
  
  # gocritic - мета-линтер с набором проверок качества кода
  gocritic:
    # Включенные категории проверок
    enabled-tags:
      # diagnostic - находит потенциальные баги и проблемы
      - diagnostic
      
      # experimental - экспериментальные проверки (могут быть false positives)
      - experimental
      
      # opinionated - стилистические правила (субъективные рекомендации)
      - opinionated
      
      # performance - находит неэффективный код (выделение памяти, копирование)
      - performance
      
      # style - проверяет стиль кода (именование, форматирование)
      - style
  
  # revive - быстрая замена golint с настраиваемыми правилами
  revive:
    rules:
      # Проверка экспортируемых идентификаторов (должны иметь комментарии)
      # Отключено: слишком много false positives для внутреннего кода
      - name: exported
        disabled: true
      
      # Проверка именования переменных (camelCase, без underscores)
      # Пример: user_name -> userName
      - name: var-naming
        disabled: false
      
      # Проверка комментариев к пакетам
      # Отключено: не все пакеты требуют детального описания
      - name: package-comments
        disabled: true
      
      # Проверка лишних else после panic/return
      - name: superfluous-else
        disabled: false
      
      # Проверка использования context.WithValue с правильными типами ключей
      - name: context-keys-type
        disabled: false

linters:
  # Отключить все линтеры по умолчанию (явно включаем только нужные)
  # Это предотвращает неожиданные изменения при обновлении golangci-lint
  disable-all: true
  
  # Явно включенные линтеры (в порядке важности)
  enable:
    # errcheck - проверка обработки ошибок (КРИТИЧНО)
    # Находит необработанные errors, предотвращает silent failures
    - errcheck
    
    # govet - официальный анализатор Go (находит подозрительные конструкции)
    # Пример: printf с неправильными аргументами, unreachable code, shadow variables
    - govet
    
    # ineffassign - обнаруживает бесполезные присваивания
    # Пример: x := 5; x = 10 (первое присваивание бесполезно)
    - ineffassign
    
    # staticcheck - мощный статический анализатор (включает gosimple, unused, staticcheck)
    # В v2.x объединяет SA*, ST*, S* проверки + упрощение кода + поиск неиспользуемого кода
    # Находит баги, несоответствия стандартам, неэффективный код, неиспользуемые элементы
    - staticcheck
    
    # gocyclo - цикломатическая сложность
    # Находит слишком сложные функции (>15 уровней вложенности)
    - gocyclo
    
    # goconst - находит магические строки/числа, которые надо вынести в константы
    # Пример: "postgres" встречается 5 раз -> const DBDriver = "postgres"
    - goconst
    
    # misspell - проверка орфографии в комментариях и строках
    # Находит опечатки типа "conection" -> "connection"
    - misspell
    
    # gosec - security проверки (SQL injection, crypto issues, file permissions)
    # Находит потенциальные уязвимости безопасности
    - gosec
    
    # unconvert - находит ненужные преобразования типов
    # Пример: int64(x) где x уже int64
    - unconvert
    
    # unparam - находит неиспользуемые параметры функций
    # Пример: func foo(x int, y int) {} где y никогда не используется
    - unparam
    
    # whitespace - находит лишние пустые строки
    # Поддерживает консистентность форматирования (не более 1 пустой строки подряд)
    - whitespace

formatters:
  # В golangci-lint v2.x форматтеры вынесены в отдельную секцию
  enable:
    # gofmt - стандартный форматтер Go
    # Проверяет соответствие кода стилю gofmt
    - gofmt
    
    # goimports - форматирование импортов
    # Группирует и сортирует импорты: stdlib -> external -> local (см. linters-settings.goimports)
    - goimports

issues:
  # Правила исключений для определённых файлов/паттернов
  exclude-rules:
    # Правило 1: Ослабить проверки для тестовых файлов
    - path: _test\.go
      linters:
        # errcheck - в тестах допустимо не проверять некоторые ошибки (setup/cleanup)
        # Пример: _ = db.Close() в тестах - это нормально
        - errcheck
        
        # gosec - в тестах допустимы небезопасные операции (тестовые данные)
        # Пример: использование math/rand вместо crypto/rand для тестовых данных
        - gosec
    
    # Правило 2: Полностью игнорировать автогенерированный код
    - path: internal/api/generated.go
      linters:
        # all - отключить ВСЕ линтеры для generated.go
        # Причина: это код сгенерирован oapi-codegen, мы не контролируем его качество
        - all
  
  # Максимальное количество проблем от одного линтера (0 = без ограничений)
  # Показывать все найденные проблемы, не обрезать вывод
  max-issues-per-linter: 0
  
  # Максимальное количество одинаковых проблем (0 = без ограничений)
  # Показывать все дубликаты, не группировать их
  max-same-issues: 0

output:
  # Формат вывода результатов линтера
  # colored-line-number - цветной вывод с номерами строк (удобно для терминала)
  # Альтернативы: json, checkstyle, github-actions
  format: colored-line-number
  
  # Печатать строки кода, в которых найдены проблемы
  # Показывает контекст ошибки прямо в выводе
  print-issued-lines: true
  
  # Печатать имя линтера, который нашёл проблему
  # Пример: [errcheck] Error return value not checked
  print-linter-name: true
