// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddReviewer(ctx context.Context, arg AddReviewerParams) error
	CountActiveUsers(ctx context.Context) (int64, error)
	CountPullRequests(ctx context.Context) (int64, error)
	CountPullRequestsByStatus(ctx context.Context, status string) (int64, error)
	CountTeams(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) error
	CreateTeam(ctx context.Context, name string) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeactivateTeamUsers(ctx context.Context, teamName string) (int64, error)
	GetActiveUsersByTeam(ctx context.Context, arg GetActiveUsersByTeamParams) ([]User, error)
	GetPRsByReviewer(ctx context.Context, reviewerID string) ([]GetPRsByReviewerRow, error)
	GetPullRequestByID(ctx context.Context, id string) (PullRequest, error)
	GetReviewersByPRID(ctx context.Context, pullRequestID string) ([]string, error)
	GetStats(ctx context.Context) (GetStatsRow, error)
	GetTeamByName(ctx context.Context, name string) (string, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUsersByTeam(ctx context.Context, teamName string) ([]User, error)
	MergePullRequest(ctx context.Context, arg MergePullRequestParams) (PullRequest, error)
	PullRequestExists(ctx context.Context, id string) (bool, error)
	RemoveReviewer(ctx context.Context, arg RemoveReviewerParams) error
	SetUserIsActive(ctx context.Context, arg SetUserIsActiveParams) error
	TeamExists(ctx context.Context, name string) (bool, error)
	UpdatePullRequest(ctx context.Context, arg UpdatePullRequestParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
	UserExists(ctx context.Context, id string) (bool, error)
}

var _ Querier = (*Queries)(nil)
