// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
)

const getStats = `-- name: GetStats :one
SELECT 
    (SELECT COUNT(*) FROM pull_requests) as total_prs,
    (SELECT COUNT(*) FROM pull_requests WHERE status = 'OPEN') as open_prs,
    (SELECT COUNT(*) FROM pull_requests WHERE status = 'MERGED') as merged_prs,
    (SELECT COUNT(*) FROM teams) as total_teams,
    (SELECT COUNT(*) FROM users) as total_users,
    (SELECT COUNT(*) FROM users WHERE is_active = true) as active_users
`

type GetStatsRow struct {
	TotalPrs    int64 `json:"total_prs"`
	OpenPrs     int64 `json:"open_prs"`
	MergedPrs   int64 `json:"merged_prs"`
	TotalTeams  int64 `json:"total_teams"`
	TotalUsers  int64 `json:"total_users"`
	ActiveUsers int64 `json:"active_users"`
}

func (q *Queries) GetStats(ctx context.Context) (GetStatsRow, error) {
	row := q.db.QueryRow(ctx, getStats)
	var i GetStatsRow
	err := row.Scan(
		&i.TotalPrs,
		&i.OpenPrs,
		&i.MergedPrs,
		&i.TotalTeams,
		&i.TotalUsers,
		&i.ActiveUsers,
	)
	return i, err
}
