// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
)

const countTeams = `-- name: CountTeams :one
SELECT COUNT(*) FROM teams
`

func (q *Queries) CountTeams(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTeams)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTeam = `-- name: CreateTeam :exec
INSERT INTO teams (name) VALUES ($1)
`

func (q *Queries) CreateTeam(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, createTeam, name)
	return err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT name FROM teams WHERE name = $1
`

func (q *Queries) GetTeamByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, getTeamByName, name)
	err := row.Scan(&name)
	return name, err
}

const teamExists = `-- name: TeamExists :one
SELECT EXISTS(SELECT 1 FROM teams WHERE name = $1)
`

func (q *Queries) TeamExists(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
