// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users WHERE is_active = true
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, team_name, is_active)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	TeamName string `json:"team_name"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.TeamName,
		arg.IsActive,
	)
	return err
}

const deactivateTeamUsers = `-- name: DeactivateTeamUsers :execrows
UPDATE users SET is_active = false WHERE team_name = $1 AND is_active = true
`

func (q *Queries) DeactivateTeamUsers(ctx context.Context, teamName string) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateTeamUsers, teamName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveUsersByTeam = `-- name: GetActiveUsersByTeam :many
SELECT id, username, team_name, is_active 
FROM users 
WHERE team_name = $1 AND is_active = true AND id != $2
ORDER BY username
`

type GetActiveUsersByTeamParams struct {
	TeamName string `json:"team_name"`
	ID       string `json:"id"`
}

func (q *Queries) GetActiveUsersByTeam(ctx context.Context, arg GetActiveUsersByTeamParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getActiveUsersByTeam, arg.TeamName, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TeamName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, team_name, is_active 
FROM users 
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.TeamName,
		&i.IsActive,
	)
	return i, err
}

const getUsersByTeam = `-- name: GetUsersByTeam :many
SELECT id, username, team_name, is_active 
FROM users 
WHERE team_name = $1
ORDER BY username
`

func (q *Queries) GetUsersByTeam(ctx context.Context, teamName string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByTeam, teamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.TeamName,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserIsActive = `-- name: SetUserIsActive :exec
UPDATE users SET is_active = $2 WHERE id = $1
`

type SetUserIsActiveParams struct {
	ID       string `json:"id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) SetUserIsActive(ctx context.Context, arg SetUserIsActiveParams) error {
	_, err := q.db.Exec(ctx, setUserIsActive, arg.ID, arg.IsActive)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users 
SET username = $2, team_name = $3, is_active = $4
WHERE id = $1
`

type UpdateUserParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	TeamName string `json:"team_name"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.TeamName,
		arg.IsActive,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, username, team_name, is_active)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) 
DO UPDATE SET 
    username = EXCLUDED.username,
    team_name = EXCLUDED.team_name,
    is_active = EXCLUDED.is_active
`

type UpsertUserParams struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	TeamName string `json:"team_name"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.Exec(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.TeamName,
		arg.IsActive,
	)
	return err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE id = $1)
`

func (q *Queries) UserExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
